version: '3'

services:
  airflow:
    image: apache/airflow:2.8.3
    ports:
      - "8080:8080"
    volumes:
      - ./Documents/Projects/CoderHouse/dags/entrega-final.py:/usr/local/airflow/dags/entrega-final.py

  my-code:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - airflow
